# Generated by Django 5.0 on 2024-01-21 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car_price', models.IntegerField()),
                ('quantity', models.PositiveBigIntegerField(default=0)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brandmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('comment', models.TextField()),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carmodel')),
            ],
        ),
    ]
