# Generated by Django 5.0 on 2024-01-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_rename_car_brand_carmodel_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='car_model',
        ),
    ]
