# Generated by Django 5.0 on 2024-01-21 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_commentmodel_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.commentmodel'),
            preserve_default=False,
        ),
    ]
