# Generated by Django 5.0 on 2024-01-21 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_carmodel_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.commentmodel'),
        ),
    ]
